//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team18App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public string Fname { get; set; }
        public string Minit { get; set; }
        public string Lname { get; set; }
        public string CLIENT_ID { get; set; }
        public string CLIENT_COMPANY { get; set; }
        public Nullable<int> Project_ID { get; set; }
    
        public virtual project project { get; set; }
    }
}
