//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team18App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project()
        {
            this.clients = new HashSet<client>();
            this.tasks = new HashSet<task>();
        }
    
        public int PROJECT_NUM { get; set; }
        public Nullable<int> PROJECT_DEPT { get; set; }
        public Nullable<int> project_manager { get; set; }
        public Nullable<decimal> PROJECT_BUDGET { get; set; }
        public Nullable<decimal> CURRENT_EXPENSES { get; set; }
        public Nullable<System.DateTime> project_deadline { get; set; }
        public Nullable<short> project_status { get; set; }
        public string project_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<client> clients { get; set; }
        public virtual department department { get; set; }
        public virtual employee employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<task> tasks { get; set; }
    }
}
