//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team18App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        public Nullable<int> project_id { get; set; }
        public int task_id { get; set; }
        public Nullable<decimal> task_budget { get; set; }
        public string task_name { get; set; }
        public Nullable<System.DateTime> task_deadline { get; set; }
        public Nullable<short> task_status { get; set; }
        public Nullable<decimal> task_expenses { get; set; }
    
        public virtual project project { get; set; }
    }
}
